### ISSUE TITLE
Revision 23 de Marzo

### ISSUE THREAD

**Issue by gera-gpz** [AnaKas-hub/P2_17100186#1]
Ok revisados T3 y T4

- Solo cambie "Value" por "value" (Con Minúscula)
- Agregar el punto y coma después del alert();

 var vi1 = parseInt(document.getElementById('vi1').Value);
 var vi2 = parseInt(document.getElementById('vi2').Value);
 var ct = parseInt(document.getElementById('ct').Value);

Pendiente T5 = Confirmar mensaje publicado en Classroom el día de hoy

**Comment by AnaKas-hub** [comment]
confirmado
